name: UpdateCSVFiles

on:
  schedule:
    - cron: '30 11,14,17,20,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Update csv files
      run: |
        python update.py
        mv -f jp-go-digital-news-news.csv.new jp-go-digital-news-news.csv
        mv -f jp-go-digital-news-meeting.csv.new jp-go-digital-news-meeting.csv
    - name: git setting
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit files
      run: |
        git add .
        git commit -m "Update csv files" -a
        git pull
        git push origin main
